### ISSUE TITLE
Wad Version 1 directory entry is missing entry count field.

### ISSUE THREAD

**Issue by Faintedsup** [CommunityDragon/Docs#3]
In wad.md, the table for the Wad Version 1 directory entry currently shows as:

Pos | Size | Format | Description
------------ | ------------- | ------------- | -------------
0 | 2 | u16 | entry header offset
2 | 2 | u16 | entry header size

but should be changed to include the entry count field as seen below.

Pos | Size | Format | Description
------------ | ------------- | ------------- | -------------
0 | 2 | u16 | entry header offset
2 | 2 | u16 | entry header size
4 | 4 | u32 | entry count

On a different note, the description for entry headers should probably mention that the data type field for version 1 WADs has 3 padding bytes appended to it.

**Comment by benoitryder** [comment]
This has been fixed. Thanks for the report!
